global:
    scrape_interval: 15s  # 모든 타겟의 기본 스크랩 간격

scrape_configs:
    - job_name: 'eureka'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['host.docker.internal:19090']  # Eureka 애플리케이션

    - job_name: 'gateway'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['host.docker.internal:19091']  # Gateway 애플리케이션

    - job_name: 'user'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['host.docker.internal:19092']  # User 애플리케이션