server:
  port: 19095

spring:
  #    profiles:
  #        active: local
  application:
    name: order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coopang_order
    username: coopang
    password: q1w2e3r4!!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 브로커 주소

springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.coopang.delivery.presentation.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.cache: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
common:
  api:
    filter:
      enabled: true
      paths:
        - /swagger-ui
        - /v3/api-docs
        - /actuator
