global:
    scrape_interval: 15s # 모든 타겟의 기본 스크랩 간격
    evaluation_interval: 15s

rule_files:
    scrape_configs:
        -   job_name: "prometheus"
            static_configs:
                -   targets: [ "localhost:9090" ] # prometheus 자체 메트릭 수집

        -   job_name: 'eureka'
            metrics_path: '/actuator/prometheus'
            static_configs:
                -   targets: [ 'host.docker.internal:19090' ]  # docker Eureka 애플리케이션
#                -   targets: [ 'localhost:19090' ]  # local Eureka 애플리케이션

        -   job_name: 'gateway'
            metrics_path: '/actuator/prometheus'
            static_configs:
                -   targets: [ 'host.docker.internal:19091' ]  # docker Gateway 애플리케이션
#                -   targets: [ 'localhost:19091' ]  # local Gateway 애플리케이션

        -   job_name: 'user'
            metrics_path: '/actuator/prometheus'
            static_configs:
                -   targets: [ 'host.docker.internal:19092' ]  # docker User 애플리케이션
#                -   targets: [ 'localhost:19092' ]  # local User 애플리케이션

        -   job_name: 'hub'
            metrics_path: '/actuator/prometheus'
            static_configs:
                -   targets: [ 'host.docker.internal:19093' ]  # docker Hub 애플리케이션
#                -   targets: [ 'localhost:19093' ]  # local Hub 애플리케이션

