spring:
    application:
        name: api-config
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


common:
    api:
        filter:
            enabled: false
            paths:
                - /users/v1/join
                - /auth/v1/login
                - /swagger-ui
                - /v3/api-docs
                - /actuator